name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    if: github.repository_owner == 'simpsonm09-org'
    uses: simpsonm09-org/simpsonm09-repo-standard/.github/workflows/lint.yml@1e4fdf788fce7b1f993ff439581d818bb12fa6b4 # repo-standard main
  aislop:
    if: github.repository_owner == 'simpsonm09-org'
    permissions:
      contents: read
      security-events: write
    uses: simpsonm09-org/simpsonm09-repo-standard/.github/workflows/aislop.yml@1e4fdf788fce7b1f993ff439581d818bb12fa6b4 # repo-standard main
  security:
    if: github.repository_owner == 'simpsonm09-org'
    permissions:
      contents: read
      security-events: write
    uses: simpsonm09-org/simpsonm09-repo-standard/.github/workflows/security.yml@1e4fdf788fce7b1f993ff439581d818bb12fa6b4 # repo-standard main

  standard:
    if: github.repository_owner == 'simpsonm09-org'
    permissions:
      contents: read
    uses: simpsonm09-org/simpsonm09-repo-standard/.github/workflows/standard.yml@1e4fdf788fce7b1f993ff439581d818bb12fa6b4 # repo-standard main
